### PR TITLE
test: fix ci/broken tests

### PR DESCRIPTION
**Pull request by callmehiphop**
Seeing a number of TS related unit test failures since merging #400.

### CODE REVIEW

**Comment by callmehiphop** [comment]
Here are the errors I was seeing for future reference

```sh
test/index.ts:360:59 - error TS2345: Argument of type '(projectId: any, name: any) => any' is not assignable to parameter of type '() => string'.

360       sandbox.stub(FakeInstance, 'formatName_').callsFake((projectId, name) => {
                                                              ~~~~~~~~~~~~~~~~~~~~~~

test/index.ts:388:59 - error TS2345: Argument of type '(projectId: any, name: any) => any' is not assignable to parameter of type '() => string'.

388       sandbox.stub(FakeInstance, 'formatName_').callsFake((projectId, name) => {
                                                              ~~~~~~~~~~~~~~~~~~~~~~

test/index.ts:399:52 - error TS2345: Argument of type '(config_: any) => void' is not assignable to parameter of type '() => any'.

399         sandbox.stub(spanner, 'request').callsFake(config_ => {
                                                       ~~~~~~~~~~~~

test/index.ts:461:53 - error TS2345: Argument of type '(name: any) => {}' is not assignable to parameter of type '() => {} | undefined'.

461         sandbox.stub(spanner, 'instance').callsFake(name => {
                                                        ~~~~~~~~~

test/session-pool.ts:1466:53 - error TS2345: Argument of type '(fn: any, interval: any) => { unref(): void; }' is not assignable to parameter of type '() => Timeout'.

1466       sandbox.stub(global, 'setInterval').callsFake((fn, interval) => {
                                                         ~~~~~~~~~~~~~~~~~~~

test/session-pool.ts:1497:53 - error TS2345: Argument of type '(fn: any, interval: any) => { unref(): void; }' is not assignable to parameter of type '() => Timeout'.

1497       sandbox.stub(global, 'setInterval').callsFake((fn, interval) => {
                                                         ~~~~~~~~~~~~~~~~~~~

test/session-pool.ts:1526:55 - error TS2345: Argument of type '(handle: any) => void' is not assignable to parameter of type '() => void'.

1526       sandbox.stub(global, 'clearInterval').callsFake(handle => {
```

**Comment by callmehiphop** [comment]
@JustinBeckwith I might need some help with Kokoro here - I can't seem to view any of the logs to inspect the failure in question.

**Comment by JustinBeckwith** [comment]
Ugh, I will try to bump the thread on blocked log access.  There's one failing test:

```
  1) Spanner
       Transactions
         read only
           should accept a read timestamp:
      Uncaught AssertionError [ERR_ASSERTION]: 0 === 1
      + expected - actual
      -0
      +1
      at transaction.run (system-test/spanner.ts:3407:20)
      at DestroyableTransform.runStream.on.on.on.on (src/transaction.ts:618:11)
      at endReadableNT (node_modules/readable-stream/lib/_stream_readable.js:1010:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

Let me re-run to see if that works (you can do this by adding the `kokoro force test` label)
